### PR TITLE
Added simple CRUD for resources into UI and updated a gem

### PR DESCRIPTION
**Pull request by eknueppel**
Added simple CRUD for resources into UI and updated a gem to fix windows issues with JS and CSS

Added validation so the 'Name' is required to be at least 2 characters

The below was added to the gemfile

Need to add this to fix windows issues and then run 'bundle update coffee-script-source'
gem 'coffee-script-source', '1.8.0'

This was a good 4 hours of work, so I hope it looks good!

### CODE REVIEW

**Comment by eknueppel** [comment]
There might be a slight conflict with what Ryan did in the application.html.erb, but they should both say application now instead of default with the gem update I did, which everyone may have to bundle update per the notes in the gemfile

**Comment by Sabotnik** [comment]
@eknueppel @RLijewski you will have to resolve the conflicts before we can merge the code, i'm taking a quick look at the actual code to see if any other changes needed

**Comment by eknueppel** [comment]
Yeah, everything is working and I even made the destroy work on windows!

**Comment by eknueppel** [comment]
Followed the suggestions for resolving conflicts on github

**Pull request merged**
